/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffdad8",
        "on-primary": "#ffffff",
        "inverse-primary": "#afcebd",
        "on-secondary-fixed": "#0d1a39",
        "primary-fixed-dim": "#afcebd",
        "error-container": "#ffdad6",
        "tertiary-container": "#4c2c2b",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#1f3a2e",
        "surface-container-highest": "#e3e2e0",
        background: "#faf9f7",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f1f1ee",
        "on-tertiary-container": "#bf9290",
        "secondary-fixed": "#dae2ff",
        surface: "#faf9f7",
        "tertiary-fixed-dim": "#ecbbb8",
        outline: "#727974",
        error: "#ba1a1a",
        tertiary: "#331717",
        "on-surface-variant": "#424844",
        "surface-dim": "#dadad8",
        secondary: "#525d80",
        "on-background": "#1a1c1b",
        "inverse-surface": "#2f312f",
        "surface-container-high": "#e9e8e6",
        "surface-bright": "#faf9f7",
        "on-primary-container": "#86a494",
        "outline-variant": "#c2c8c2",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#603e3c",
        "on-primary-fixed-variant": "#314c40",
        "secondary-container": "#cad6ff",
        "surface-tint": "#486457",
        "surface-container-low": "#f4f3f1",
        "on-surface": "#1a1c1b",
        "secondary-fixed-dim": "#bac5ee",
        "on-secondary-fixed-variant": "#3a4667",
        "surface-container": "#eeeeeb",
        primary: "#082419",
        "on-primary-fixed": "#042016",
        "primary-fixed": "#cbead8",
        "on-tertiary-fixed": "#2f1313",
        "surface-variant": "#e3e2e0",
        "on-secondary-container": "#515c7f",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        content_max_width: "800px",
        gutter: "24px",
        stack_sm: "12px",
        container_padding: "40px",
        stack_md: "24px",
        unit: "8px",
        stack_lg: "48px",
      },
      fontFamily: {
        code: ["JetBrains Mono", "monospace"],
        h1: ["Newsreader", "serif"],
        "editor-text": ["Noto Serif", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        h3: ["Newsreader", "serif"],
        "display-lg": ["Newsreader", "serif"],
        h2: ["Newsreader", "serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
        serif: ["Newsreader", "serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        code: ["14px", { lineHeight: "1.4", fontWeight: "400" }],
        h1: ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "editor-text": ["17px", { lineHeight: "1.8", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": [
          "12px",
          { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        h3: ["20px", { lineHeight: "1.4", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.1", fontWeight: "600" }],
        h2: ["24px", { lineHeight: "1.3", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};