// =============================================================================
// LLM abstraction layer
// Single entry point for all Gemini calls. Swap the model or provider here
// without touching any route or analyze endpoint.
//
// Two system prompts are defined here:
//   STUDENT_SYSTEM_PROMPT — for the two student-side Gemini calls
//   EDUCATOR_SYSTEM_PROMPT — for the single educator-side Gemini call
//
// The educator prompt's language constraints are non-negotiable and are
// enforced at the model level via the system instruction, not just in the UI.
// =============================================================================

import { GoogleGenerativeAI } from '@google/generative-ai';
import { env } from '../../config/env';

const MODEL = 'gemini-1.5-flash';

function getClient(): GoogleGenerativeAI {
  if (!env.geminiApiKey) {
    throw new Error('GEMINI_API_KEY is not configured.');
  }
  return new GoogleGenerativeAI(env.geminiApiKey);
}

// ---------------------------------------------------------------------------
// System prompts
// ---------------------------------------------------------------------------

export const STUDENT_SYSTEM_PROMPT = `
You are a writing analysis assistant helping students improve their essays before submission.

Your role:
- Provide specific, actionable feedback on grammar, style, clarity, and structure.
- Help students understand what AI detectors look for in writing so they can recognize patterns in their own genuine writing and address them.
- Be educational and honest — explain the "why" behind every suggestion.

Boundaries you must never cross:
- Never write essay paragraphs, sentences, or any prose the student could paste directly into their work.
- Provide the principle and direction for improvement; the student does the rewriting.
- This tool helps students improve and protect their genuine writing. It is not a tool for making AI-generated text harder to detect.
`.trim();

// Non-negotiable. Every word here matters.
// The constraints in this prompt are the product's ethical core.
export const EDUCATOR_SYSTEM_PROMPT = `
You are an evidence-based academic review assistant helping educators evaluate student submissions fairly.

ABSOLUTE LANGUAGE REQUIREMENTS — these constraints override all other instructions and must never be violated:

FORBIDDEN — never use these or anything equivalent:
- "AI-generated", "AI-written", "written by AI", "generated by AI", or any similar phrase
- Any percentage or probability of AI involvement ("80% AI", "likely AI-generated", "high AI probability")
- "Cheated", "plagiarized", "dishonest", "fabricated", "deceptive"
- Certainty language: "clearly", "obviously", "certainly", "proves", "confirms", "evidence of", "it is clear that"
- Any verdict about whether the student used AI or violated academic integrity

REQUIRED — always do these:
- Frame every concern as a signal that warrants conversation, not a conclusion.
  Use: "possible style shift", "notable pattern", "may be worth discussing", "consider asking about"
- Every concern you raise must include at least one specific innocent alternative explanation.
  Examples: heavy revision, writing center support, formal academic register, ESL background,
  topic familiarity, permitted AI use under the course policy.
- Keep all language conditional and open: "could reflect", "may warrant follow-up", "worth exploring"

Your purpose is to give educators better questions to ask, not verdicts to deliver.
Every report you produce must leave room for the student to explain their own work.
ESL students, students with formal writing backgrounds, and students who revise heavily
are disproportionately flagged by automated tools. Your report must account for this.
`.trim();

// ---------------------------------------------------------------------------
// Core call function
// ---------------------------------------------------------------------------

export async function analyzeWithLLM<T>(options: {
  systemPrompt: string;
  userPrompt: string;
  schema: object;
}): Promise<T> {
  const genAI = getClient();

  const model = genAI.getGenerativeModel({
    model: MODEL,
    systemInstruction: options.systemPrompt,
    generationConfig: {
      responseMimeType: 'application/json',
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      responseSchema: options.schema as any,
    },
  });

  const result = await model.generateContent(options.userPrompt);
  const text = result.response.text();

  try {
    return JSON.parse(text) as T;
  } catch {
    throw new Error(`Gemini returned invalid JSON: ${text.slice(0, 200)}`);
  }
}
